name: Deploy to EC2 via SSM

on:
  push:
    branches: [main]
  workflow_dispatch:  # Manual trigger from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write     # Needed for GitHub OIDC auth
      contents: read      # Allows checkout of code

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: us-east-2  # Use your EC2 region

    - name: Deploy index.html to EC2 via SSM
      run: |
        # Encode index.html to Base64
        ENCODED=$(base64 index.html)

        # Send the file to EC2 and restart Apache
        aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --comment "Deploy index.html from GitHub Actions" \
          --instance-ids i-09cdd0bfff5d5364b \
          --parameters "commands=[\"echo '$ENCODED' | base64 -d | sudo tee /var/www/html/index.html > /dev/null\", \"sudo systemctl restart apache2\"]" \
          --region us-east-2 \
          --output text
