name: Deploy to EC2 via SSM

on:
  push:
    branches: [main]
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write     # Required for GitHub OIDC authentication
      contents: read      # Required to access the repository content

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: us-east-2 # Replace with your EC2's region if different

    - name: Deploy index.html to EC2 via SSM
      run: |
        aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --comment "Deploy index.html from GitHub Actions" \
          --instance-ids i-09cdd0bfff5d5364b \
          --parameters 'commands=["echo '\''$(cat index.html)'\'' | sudo tee /var/www/html/index.html > /dev/null", "sudo systemctl restart apache2"]' \
          --output text
